build:
	docker build -t waggle/beehive-loader-raw .

start:
	systemctl start waggle/beehive-loader-raw

stop:
	systemctl stop waggle/beehive-loader-raw

restart:
	systemctl restart waggle/beehive-loader-raw
