build:
	docker build -t waggle/beehive-worker-gps-sense .

start:
	systemctl start beehive-worker-gps-sense

stop:
	systemctl stop beehive-worker-gps-sense

restart:
	systemctl restart beehive-worker-gps-sense
