#!/bin/sh

set -e

for task in $(ls tasks | sort -r); do
  echo starting $task
  ../export-decoded-datasets-csv-v3 < tasks/$task
  gzip -f datasets/3/*/*.csv || true
  rm tasks/$task
  echo completed $task
done
