#!/usr/bin/env python3
from cassandra.cluster import Cluster
from itertools import groupby
import os

os.makedirs('tasks', exist_ok=True)

cluster = Cluster(connect_timeout=30, control_connection_timeout=30)
session = cluster.connect('waggle')

rows = list(session.execute('SELECT DISTINCT node_id, date FROM sensor_data_raw'))
rows.sort(key=lambda r: r.date, reverse=True)

for date, datasets in groupby(rows, key=lambda r: r.date):
    with open(os.path.join('tasks', date), 'w') as file:
        for r in datasets:
            print(r.node_id[-12:].lower(), r.node_id, r.date, file=file)
