#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import requests
import re
import sys


def match_node_id(s):
    return re.match(r'[0-9a-fA-F]{16}', s)


for node_id in sys.argv[1:]:
    if not match_node_id(node_id):
        print(node_id, 'invalid')
        continue

    r = requests.get('http://127.0.0.1:24181/node?{}'.format(node_id))
    print(r.text)
