#!/usr/bin/env python3
from glob import glob
import os
import requests
from jinja2 import Template
import json


r = requests.get('http://beehive1.mcs.anl.gov/api/1/nodes/')

nodes = []

for item in r.json()['data'].values():
    nodes.append({
        'id': item['node_id'][-12:],
        'name': item.get('name', ''),
        'description': item.get('description', ''),
        'url': '{}.json'.format(item['node_id'][-12:]),
    })

with open('static/index.json', 'w') as f:
    json.dump(nodes, f)

for node in nodes:
    try:
        datasets = []

        # for filename in glob('datasets/2raw/{}/*.csv.gz'.format(node['id'])):
        #     datasets.append({
        #         'url': filename,
        #         'date': filename.split('/')[-1].split('.')[0],
        #         'version': '2 Raw',
        #     })

        for filename in glob('datasets/2/{}/*.csv.gz'.format(node['id'])):
            datasets.append({
                'url': filename,
                'date': filename.split('/')[-1].split('.')[0],
                'version': '2',
            })

        node['datasets'] = sorted(datasets, key=lambda r: (r['version'], r['date']))

        if node['datasets']:
            node['latest'] = max([dataset['date'] for dataset in node['datasets']])

    except FileNotFoundError:
        continue

index_template = Template(open('templates/index.html').read())
node_template = Template(open('templates/node.html').read())

os.makedirs('static', exist_ok=True)

with open('static/index.html', 'w') as f:
    f.write(index_template.render(nodes=nodes))

for node in nodes:
    with open('static/{}.json'.format(node['id']), 'w') as f:
        json.dump(node['datasets'], f)

    # write csv version
    with open('static/{}.csv'.format(node['id']), 'w') as f:
        for dataset in node['datasets']:
            row = [dataset['date'], dataset['version'], dataset['url']]
            print(';'.join(row), file=f)

    with open('static/{}.html'.format(node['id']), 'w') as f:
        f.write(node_template.render(node=node))
