#!/bin/sh
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

set -e

if [ $# -ne 2 ]; then
  echo "usage: $0 taskdir datadir"
  exit 1
fi

taskdir=$1
datadir=$2

for task in $(ls $taskdir | sort -r); do
  echo starting $task
  ./export-datasets -p 1 $2 < $taskdir/$task
  rm $taskdir/$task
  echo completed $task
done
