#!/usr/bin/env python3
import argparse
from cassandra.cluster import Cluster
from itertools import groupby
import os

parser = argparse.ArgumentParser()
parser.add_argument('taskdir', help='directory where tasks will be stored')
args = parser.parse_args()

os.makedirs(args.taskdir, exist_ok=True)

cluster = Cluster()
session = cluster.connect('waggle')

rows = list(session.execute('SELECT DISTINCT node_id, date FROM sensor_data_raw'))
rows.sort(key=lambda r: r.date, reverse=True)

for date, datasets in groupby(rows, key=lambda r: r.date):
    with open(os.path.join(args.taskdir, date), 'w') as file:
        for r in datasets:
            print(r.node_id, r.date, file=file)
