#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import fileinput
from datetime import datetime
import sys

now = datetime.now()

for line in map(str.strip, fileinput.input()):
    try:
        fields = line.split()
        date = datetime.strptime(fields[1], '%Y-%m-%d')

        if (now - date).days <= 3:
            print(line, flush=True)
    except KeyboardInterrupt:
        break
    except Exception as e:
        print(e, flush=True, file=sys.stderr)
