#!/bin/sh
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
# ...just slice last n characters and see if matches /1/
awk '$3 ~ /1$/ || $3 ~ /1.$/ || $3 ~ /1..$/ || $3 ~ /1...$/ || $3 ~ /1....$/ || $3 ~ /1.....$/ || $3 ~ /1......$/' $@
