#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import argparse
import matplotlib.pyplot as plt
import re
import sys

cmap = 'bone'

parser = argparse.ArgumentParser()
parser.add_argument('outfile', nargs='?')
args = parser.parse_args()

img = []

for line in sys.stdin:
    up = max(re.findall('[01]+', line), key=len)
    img.append([int(c) for c in up])

if args.outfile:
    plt.imsave(args.outfile, img, cmap=cmap)
else:
    plt.figure()
    plt.imshow(img, cmap=cmap)
    plt.show()
