#!/usr/bin/env python3
import argparse
import matplotlib.pyplot as plt
import re
import sys

parser = argparse.ArgumentParser()
parser.add_argument('outfile', nargs='?')
args = parser.parse_args()

img = []

for line in sys.stdin:
    up = max(re.findall('[01]+', line), key=len)
    img.append([int(c) for c in up])

if args.outfile:
    plt.imsave(args.outfile, img)
else:
    plt.figure()
    plt.imshow(img)
    plt.show()
