#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import subprocess
import re
import os

BEEHIVE_ROOT = os.environ['BEEHIVE_ROOT']


output = subprocess.check_output(['docker', 'exec', '-ti', 'beehive-rabbitmq', 'rabbitmqctl', 'list_users']).decode()
existing_users = set(re.findall('node[\-0-9A-Fa-f]+', output))

for username in existing_users:
    subprocess.check_output(['docker', 'exec', '-ti', 'beehive-rabbitmq', 'rabbitmqctl', 'clear_password', username])

    config_access = '^to-{}$'.format(username)
    write_access = '^data|messages$'
    read_access = '^to-{}$'.format(username)

    subprocess.check_output([
        'docker',
        'exec',
        '-ti',
        'beehive-rabbitmq',
        'rabbitmqctl',
        'set_permissions',
        username,
        config_access,
        write_access,
        read_access,
    ])
