#!/usr/bin/env python3
import subprocess
import re
import os
import glob


output = subprocess.check_output(['docker', 'exec', '-ti', 'beehive-rabbitmq', 'rabbitmqctl', 'list_users']).decode()
existing_users = set(re.findall('node[0-9]+', output))

cert_users = set()

for match in glob.glob('/Users/Sean/beehive-testing/waggle/SSL/nodes/node_*'):
    certfile = os.path.join(match, 'cert.pem')
    output = subprocess.check_output(['openssl', 'x509', '-noout', '-subject', '-in', certfile]).decode()
    username = re.search('CN=(node[0-9A-Fa-f]+)', output).group(1)
    cert_users.add(username)

add_users = cert_users - existing_users
del_users = existing_users - cert_users

for username in add_users:
    print('add', username)
    subprocess.check_output(['docker', 'exec', '-ti', 'beehive-rabbitmq', 'rabbitmqctl', 'add_user', username, ''])
    subprocess.check_output(['docker', 'exec', '-ti', 'beehive-rabbitmq', 'rabbitmqctl', 'clear_password', username])

for username in del_users:
    print('drop', username)
    subprocess.check_output(['docker', 'exec', '-ti', 'beehive-rabbitmq', 'rabbitmqctl', 'delete_user', username])
