build:
	docker build -t waggle/beehive-worker-alphasense .

start:
	systemctl start beehive-worker-alphasense

stop:
	systemctl stop beehive-worker-alphasense

restart:
	systemctl restart beehive-worker-alphasense
