build:
	docker build -t waggle/beehive-worker-coresense .

start:
	systemctl start beehive-worker-coresense

stop:
	systemctl stop beehive-worker-coresense

restart:
	systemctl restart beehive-worker-coresense
