#!/usr/bin/python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

import docker
import re
import sys

import waggle.beehive.node as node


if len(sys.argv) < 2:
  print('Usage: get-node-id <partial-node-id>')
  sys.exit(2)

node_ids = node.find_ids(sys.argv[1])
if len(node_ids) > 0:
  for node_id in node_ids:
    print(node_id)
else:
  sys.exit(1)
