#!/usr/bin/python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

import sys

import waggle.beehive.node as node



if len(sys.argv) == 1:
  print("Usage: get-node-ssh-metrics <partial_node_id>")
  sys.exit(1)

metrics = node.rabbitmq_metrics(sys.argv[1])
if 'node_id' in metrics:
  print(metrics)
else:
  sys.exit(1)
